# Connect four with Deep Q-Network vs Random agent from Tianshou

In this notebook, the created custom gym environment of connect four is played using a Deep Q-Network (DQN) agent which plays against a random agent.
We use the powerful [Tianshou library](https://github.com/thu-ml/tianshou) for this.
Using Tianshou in a multi-agent environment like ours meant we had to create yet another version of the Gym environment now based on an `AECEnv` environment.

The methodology used in this notebook is largely equal to those of the random agents in the `1-learning-connect-four-random-agents-tianshou.ipynb` notebook and the tutorial on [multi-agent tic-tac-toe learning from Tianshou](https://tianshou.readthedocs.io/en/master/tutorials/tictactoe.html).


<hr><hr>

## Table of Contents

- Contact information
- Checking requirements
  - Correct Anaconda environment
  - Correct module access
  - Correct CUDA access
- Training DQN vs Random agent on connect four Gym
  - Create the Gym environment
  - Building the environment
  - Implementing the DQN policy
  - Building agents
  - Function for letting agents learn
  - Function for watching learned agent
  - Doing the experiment
- Discussion

<hr><hr>

## Contact information

| Name             | Student ID | VUB mail                                                  | Personal mail                                               |
| ---------------- | ---------- | --------------------------------------------------------- | ----------------------------------------------------------- |
| Lennert Bontinck | 0568702    | [lennert.bontinck@vub.be](mailto:lennert.bontinck@vub.be) | [info@lennertbontinck.com](mailto:info@lennertbontinck.com) |



<hr><hr>

## Checking requirements

### Correct Anaconda environment

The `rl-project` anaconda environment should be active to ensure proper support. Installation instructions are available on [the GitHub repository of the RL course project and homeworks](https://github.com/pikawika/vub-rl).

In [1]:
####################################################
# CHECKING FOR RIGHT ANACONDA ENVIRONMENT
####################################################

import os
from platform import python_version

print(f"Active environment: {os.environ['CONDA_DEFAULT_ENV']}")
print(f"Correct environment: {os.environ['CONDA_DEFAULT_ENV'] == 'rl-project'}")
print(f"\nPython version: {python_version()}")
print(f"Correct Python version: {python_version() == '3.8.10'}")

Active environment: rl-project
Correct environment: True

Python version: 3.8.10
Correct Python version: True


<hr>

### Correct module access

The following code block will load in all required modules and show if the versions match those that are recommended.

In [3]:
####################################################
# LOADING MODULES
####################################################

# Allow reloading of libraries
import importlib

# Plotting
import matplotlib; print(f"Matplotlib version (3.5.1 recommended): {matplotlib.__version__}")
import matplotlib.pyplot as plt

# Argparser
import argparse

# More data types
import typing
import numpy as np

# Pygame
import pygame; print(f"Pygame version (2.1.2 recommended): {pygame.__version__}")

# Gym environment
import gym; print(f"Gym version (0.21.0 recommended): {gym.__version__}")

# Tianshou for RL algorithms
import tianshou as ts; print(f"Tianshou version (0.4.8 recommended): {ts.__version__}")

# Torch is a popular DL framework
import torch; print(f"Torch version (1.12.0 recommended): {torch.__version__}")

# PPrint is a pretty print for variables
from pprint import pprint

# Our custom connect four gym environment
import sys
sys.path.append('../')
import gym_connect4_pygame.envs.ConnectFourPygameEnvV2 as cfgym
importlib.invalidate_caches()
importlib.reload(cfgym)

# Time for allowing "freezes" in execution
import time;

# Allow for copying objects in a non reference manner
import copy

# Used for updating notebook display
from IPython.display import clear_output

Matplotlib version (3.5.1 recommended): 3.5.1
Pygame version (2.1.2 recommended): 2.1.2
Gym version (0.21.0 recommended): 0.21.0
Tianshou version (0.4.8 recommended): 0.4.8
Torch version (1.12.0 recommended): 1.12.0.dev20220520+cu116


<hr>

### Correct CUDA access

The installation instructions specify how to install PyTorch with CUDA 11.6.
The following code block tests if this was done successfully.

In [4]:
####################################################
# CUDA VALIDATION
####################################################

# Check cuda available
print(f"CUDA is available: {torch.cuda.is_available()}")

# Show cuda devices
print(f"\nAmount of connected devices supporting CUDA: {torch.cuda.device_count()}")

# Show current cuda device
print(f"\nCurrent CUDA device: {torch.cuda.current_device()}")

# Show cuda device name
print(f"Cuda device 0 name: {torch.cuda.get_device_name(0)}")

CUDA is available: True

Amount of connected devices supporting CUDA: 1

Current CUDA device: 0
Cuda device 0 name: NVIDIA GeForce GTX 970


<hr><hr>

## Training DQN vs Random agent on connect four Gym

Our connect four gym setup requires two agents, one for each player.
To reduce complexity, agents will always play as the same player, e.g. always as player 1.
It is important to note that connect four is a *solved game*.
According to [The Washington Post](https://www.washingtonpost.com/news/wonk/wp/2015/05/08/how-to-win-any-popular-game-according-to-data-scientists/):

> Connect Four is what mathematicians call a "solved game," meaning you can play it perfectly every time, no matter what your opponent does. You will need to get the first move, but as long as you do so, you can always win within 41 moves.

<hr>

### Create the Gym environment

Whilst our first connect four implementation (V1) was playable in a multi-agent manner through a manual game loop, as is done for random agents in the experimental notebook `2-testing-custom-gym-environment.ipynb`, it is hard to use most of the popular RL libraries for this environment.
That is because the Gym environment was originally made with single agent games in mind and there is no real standard on how to write multi-agent environments.
Thus, Tianshou, which offers some multi-agent support, didn't work well with this version of the Gym environment.
To tackle this, we created a V2, which is a rework of V1 to follow the standards of a *Petting Zoo* environment.
[Petting zoo](https://www.pettingzoo.ml/) is a library that offers many Gym environments extended to be multi-agent which uses wrapper classes and base classes so that each multi-agent environment follows the same guidelines.

These guidelines are exactly what V2 of our connect four implementation is adopted towards.
The environment is now a subclass of `AECEnv` rather than a `gym.Env`, which follows a similar approach but requires far more attributes and more complex observation and action spaces so that each agent has its own, even if they are all equal.

We note that we only found out about this library after running into trouble making our V1 work with libraries that support Gym training.
We could have searched for online implementations of e.g. Deep Q-Network (DQN) that allows training using the gym gaming loop used in the experimental notebook `2-testing-custom-gym-environment.ipynb`. 
Nonetheless, this would likely require a lot of manual work which is not ideal for the goal of this research, which focuses on reducing work for game developers.
Thus, the decision was made to create this V2 of the environment based on Petting Zoo environments.

As a final note, we noticed there was a Connect Four implementation of Petting Zoo.
This implementation differs from ours in several ways.
Their observation space consists of multiple variants of the board, namely one with only the opponent's coin and the agent's coins and it uses action masks to not allow placing coins in full columns.
We use a singular observation space of the complete board, which is the location of both agent's coins and the free spaces, corresponding to what a human would see.
Adding to this, we also don't programmatically disallow placing a coin in a full column but rather punish the user for trying that action and leave the board unchanged and let the agent play again.
There are more differences then the ones listed here and the visual game is also completely different.

In [5]:
####################################################
# SETTING UP THE GYM ENVIRONMENT
####################################################

# Create an instance of the environment to be used
# V2 is used as this contains edits for Tianshou
# We use the Tianshou PettingZooEnv wrapper for multiagent support
env = ts.env.PettingZooEnv(cfgym.env())

# Get information about the environment
print(f"Observation space: {env.observation_space}")
print(f"\nAction space: {env.action_space}")

# Reset the environment to start from a clean state, returns the initial observation
observation = env.reset()

print("\n Initial player id:")
print(observation["agent_id"])

print("\n Initial observation:")
print(observation["obs"])

print("\n Initial mask:")
print(observation["mask"])

# Clean unused variables
del observation
del env

Observation space: Dict(action_mask:Box([0 0 0 0 0 0 0], [1 1 1 1 1 1 1], (7,), int8), observation:Box([[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]], [[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]], (6, 7), int8))

Action space: Discrete(7)

 Initial player id:
player_1

 Initial observation:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

 Initial mask:
[True, True, True, True, True, True, True]


<hr>

### Building the environment

We build a simple function to get the environment the agent will play in

In [6]:
####################################################
# CONNECT FOUR V2 ENVIRONMENT
####################################################

def get_env():
    """
    Returns the connect four gym environment V2 altered for Tianshou and Petting Zoo compatibility.
    Already wrapped with a ts.env.PettingZooEnv wrapper.
    """
    return ts.env.PettingZooEnv(cfgym.env())

<hr>

### Implementing the DQN policy

The DQN policy for the agent is configured and set up below.

In [7]:
####################################################
# DQN POLICY
####################################################

def cf_dqn_policy(state_shape: tuple,
                  action_shape: tuple,
                  optim: typing.Optional[torch.optim.Optimizer] = None,
                  learning_rate: float =  0.0001,
                  gamma: float = 0.7, # Smaller gamma favours "faster" win
                  n_step: int = 3, # Number of steps to look ahead
                  target_update_freq: int = 320,
                  hidden_sizes: list = [128, 128, 128, 128]):
    # Use cuda device if possible
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    
    # Network to be used for DQN
    ## Set to use the CUDA device if possible
    net = ts.utils.net.common.Net(state_shape= state_shape,
                                  action_shape= action_shape,
                                  hidden_sizes= hidden_sizes,
                                  device= device).to(device)
    
    # Default optimizer is an adam optimizer with the argparser learning rate
    if optim is None:
        optim = torch.optim.Adam(net.parameters(), lr= learning_rate)
        
    # Our agent DQN policy
    return ts.policy.DQNPolicy(model= net,
                               optim= optim,
                               discount_factor= gamma,
                               estimation_step= n_step,
                               target_update_freq= target_update_freq)

<hr>

### Building agents

We can now adopt the `get_agents` function from Tianshou to build our DQN agents for the game.

NOTE: agent 2 is random for now whilst agent 1 will use DQN.

In [8]:
####################################################
# AGENT CREATION
####################################################

def get_agents(agent_player1: typing.Optional[ts.policy.BasePolicy] = None,
               agent_player2: typing.Optional[ts.policy.BasePolicy] = None,
               optim: typing.Optional[torch.optim.Optimizer] = None,
               resume_path_player_1: str = '', # Path to file to resume agent training from
               ) -> typing.Tuple[ts.policy.BasePolicy, torch.optim.Optimizer, list]:
    """
    Gets a multi agent policy manager, optimizer and player ids for the connect four V2 gym environment.
    Per default this returns 
        - Multi agent manager for agent 1 using DQN and agent 2 using random policy
        - Adam optimizer
        - ['player_1', 'player_2'] from the connect four environment
    """
    
    # Get the environment to play in (Connect four gym V2)
    env = get_env()
    
    # Get the observation space from the environment, depending on typo of space (ternary operator)
    observation_space = env.observation_space['observation'] if isinstance(env.observation_space, gym.spaces.Dict) else env.observation_space
    
    # Set the arguments
    state_shape = observation_space.shape or observation_space.n
    action_shape = env.action_space.shape or env.action_space.n
    
    # Configure agent player 1 to be a DQN if no policy is passed.
    if agent_player1 is None:
        # Our agent1 uses a DQN policy
        agent_player1 = cf_dqn_policy(state_shape= state_shape,
                                      action_shape= action_shape,
                                      optim= optim)
        
        # If we resume our agent we need to load the previous config
        if resume_path_player_1:
            agent_player1.load_state_dict(torch.load(resume_path_player_1))

    # Configure agent player 2 to be a DQN if no policy is passed
    #   or a copy of player 1 with the specified path.
    if agent_player2 is None:
        # Our agent2 uses a random policy per default for now
        agent_player2 = ts.policy.RandomPolicy()

    # Player 1 agent is DQN, other is random
    agents = [agent_player1, agent_player2]
        
    # Our policy depends on the order of the agents
    policy = ts.policy.MultiAgentPolicyManager(agents, env)
    
    # Return our policy, optimizer and the available agents in the environment
    # Per default: 
    #   - Multi agent manager for agent 1 using DQN and agent 2 using random policy
    #   - Adam optimizer
    #   - ['player_1', 'player_2'] from the connect four environment
    
    return policy, optim, env.agents

<hr>

### Function for letting agents learn

We can now adopt the `train_agent` function from Tianshou to allow our DQN and random agent for the game to learn.

In [9]:
####################################################
# AGENT TRAINING
####################################################

def train_agent(filename: str = "dqn_vs_random",
                agent_player1: typing.Optional[ts.policy.BasePolicy] = None,
                agent_player2: typing.Optional[ts.policy.BasePolicy] = None,
                optim: typing.Optional[torch.optim.Optimizer] = None,
                training_env_num: int = 10,
                testing_env_num: int = 10,
                buffer_size: int = 2^14, # 16 384
                batch_size: int = 64,
                epochs: int = 50,
                step_per_epoch: int = 1000,
                step_per_collect: int = 10,
                update_per_step: float = 0.1,
                testing_eps: float = 0.05,
                training_eps: float = 0.1,
                ) -> typing.Tuple[dict, ts.policy.BasePolicy]:
    """
    Trains two agents in the connect four V2 environment and saves their best model and logs.
    Returns:
        - result from offpolicy_trainer
        - final version of agent 1
        - final version of agent 2
    """

    # ======== environment setup =========
    train_envs = ts.env.DummyVectorEnv([get_env for _ in range(training_env_num)])
    test_envs = ts.env.DummyVectorEnv([get_env for _ in range(testing_env_num)])
    
    # set the seed for reproducibility
    np.random.seed(1998)
    torch.manual_seed(1998)
    train_envs.seed(1998)
    test_envs.seed(1998)

    # ======== agent setup =========
    # Gets our agents from the previously made function
    # Per default: 
    #   - Multi agent manager for agent 1 using DQN and agent 2 using random policy
    #   - Adam optimizer
    #   - ['player_1', 'player_2'] from the connect four environment
    policy, optim, agents = get_agents(agent_player1=agent_player1,
                                       agent_player2=agent_player2,
                                       optim=optim)

    # ======== collector setup =========
    # Make a collector for the training environments
    train_collector = ts.data.Collector(policy= policy,
                                        env= train_envs,
                                        buffer= ts.data.VectorReplayBuffer(buffer_size, len(train_envs)),
                                        exploration_noise= True)
    
    # Make a collector for the testing environments
    test_collector = ts.data.Collector(policy= policy,
                                       env= test_envs,
                                       exploration_noise= True)
    
    # Uncomment below if you want to set epsilon in epsilon policy
    # policy.set_eps(1)
    
    # Collect data fot the training evnironments
    train_collector.collect(n_step= batch_size * training_env_num)
    
    # ======== ensure folders exist =========
    if not os.path.exists(os.path.join('./logs', 'paper_notebooks', '2', filename)):
        os.makedirs(os.path.join('./logs', 'paper_notebooks', '2', filename))
    if not os.path.exists(os.path.join('./saved_variables', 'paper_notebooks', '2', filename)):
        os.makedirs(os.path.join('./saved_variables', 'paper_notebooks', '2', filename))

    # ======== tensorboard logging setup =========
    # Allows to save the training progress to tensorboard compatable logs
    log_path = os.path.join('./logs', 'paper_notebooks', '2', filename)
    writer = torch.utils.tensorboard.SummaryWriter(log_path)
    logger = ts.utils.TensorboardLogger(writer)

    # ======== callback functions used during training =========
    # We want to save our best policy
    def save_best_fn(policy):
        """
        Callback to save the best model
        """
        # Save agent 1
        model_save_path = os.path.join('./saved_variables', 'paper_notebooks', '2', filename, 'best_policy_agent1.pth')
        torch.save(policy.policies[agents[0]].state_dict(), model_save_path)
        
        # Save agent 2
        model_save_path = os.path.join('./saved_variables', 'paper_notebooks', '2', filename, 'best_policy_agent2.pth')
        torch.save(policy.policies[agents[1]].state_dict(), model_save_path)
        
        # Save agent2

    def stop_fn(mean_rewards):
        """
        Callback to stop training when we've reached the win rate
        """
        return mean_rewards >= 7 # (win = 10, 70% win without invalid moves = mean of 7)

    def train_fn(epoch, env_step):
        """
        Callback for training
        """        
        # Agent 1
        policy.policies[agents[0]].set_eps(training_eps)

    def test_fn(epoch, env_step):
        """
        Callback for testing
        """        
        # Agent 1
        policy.policies[agents[0]].set_eps(testing_eps)

    def reward_metric(rews):
        """
        Callback for reward collection
        """
        # We are only interested in optimizing agent 1 and thus only agent 1 score
        return rews[:, 0]

    # trainer
    result = ts.trainer.offpolicy_trainer(policy= policy,
                                          train_collector= train_collector,
                                          test_collector= test_collector,
                                          max_epoch= epochs,
                                          step_per_epoch= step_per_epoch,
                                          step_per_collect= step_per_collect,
                                          episode_per_test= testing_env_num,
                                          batch_size= batch_size,
                                          train_fn= train_fn,
                                          test_fn= test_fn,
                                          # Stop function to stop before specified amount of epochs
                                          #stop_fn= stop_fn
                                          save_best_fn= save_best_fn,
                                          update_per_step= update_per_step,
                                          logger= logger,
                                          test_in_train= False,
                                          reward_metric= reward_metric)

    return result, policy.policies[agents[0]], policy.policies[agents[1]]

<hr>

### Function for watching learned agent

When an agent has learned, we can watch the learned policy in action.

In [10]:
####################################################
# WATCHING THE LEARNED POLICY IN ACTION
####################################################

def watch(numer_of_games:int = 3,
          agent_player1: typing.Optional[ts.policy.BasePolicy] = None,
          agent_player2: typing.Optional[ts.policy.BasePolicy] = None,
          test_epsilon: float = 0.05, # For the watching we act completely greedy but low random for not getting stuck on invalid move
          render_speed: float = 0.15, # Amount of seconds to update frame/ do a step
          ) -> None:
    
    # Get the connect four V2 environment (must be a list)
    env= ts.env.DummyVectorEnv([get_env])
    
    # Get the agents from the trained agents
    policy, optim, agents = get_agents(agent_player1= agent_player1,
                                       agent_player2= agent_player2)
    
    # Evaluate the policy
    policy.eval()
    
    # Set the testing policy epsilon for our first agent
    policy.policies[agents[0]].set_eps(test_epsilon)
    
    # Collect the test data
    collector = ts.data.Collector(policy= policy,
                                  env= env,
                                  exploration_noise= True)
    
    # Render games in human mode to see how it plays
    result = collector.collect(n_episode= numer_of_games, render= render_speed)
    
    # Close the environment aftering collecting the results
    # This closes the pygame window after completion
    env.close()
    
    # Get the rewards and length from the test trials
    rewards, length = result["rews"], result["lens"]
    
    # Print the final reward for the first agent
    print(f"Average steps of game:  {length.mean()}")
    print(f"Final mean reward agent 1: {rewards[:, 0].mean()}, std: {rewards[:, 0].std()}")
    print(f"Final mean reward agent 2: {rewards[:, 1].mean()}, std: {rewards[:, 1].std()}")

<hr>

### Doing the experiment

We now do the experiment with using our previously created functions.

In [10]:
####################################################
# EXPERIMENT: TRAINING AGENTS
####################################################

# Train the agent
off_policy_traininer_results, final_agent_player1, final_agent_player2 = train_agent(epochs= 50)

Epoch #1: 1001it [00:02, 464.52it/s, env_step=1000, len=12, n/ep=0, n/st=10, player_1/loss=1191.006, rew=-10.00]       


Epoch #1: test_reward: -927.400000 ± 1791.873891, best_reward: -927.400000 ± 1791.873891 in #1


Epoch #2: 1001it [00:01, 813.42it/s, env_step=2000, len=9, n/ep=0, n/st=10, player_1/loss=70.863, rew=10.00]           


Epoch #2: test_reward: -326.000000 ± 672.814387, best_reward: -326.000000 ± 672.814387 in #2


Epoch #3: 1001it [00:01, 821.12it/s, env_step=3000, len=10, n/ep=0, n/st=10, player_1/loss=47.418, rew=10.00]          


Epoch #3: test_reward: -3966.800000 ± 11930.400000, best_reward: -326.000000 ± 672.814387 in #2


Epoch #4: 1001it [00:01, 819.74it/s, env_step=4000, len=7, n/ep=0, n/st=10, player_1/loss=49.881, rew=10.00]           


Epoch #4: test_reward: -4253.700000 ± 12080.687373, best_reward: -326.000000 ± 672.814387 in #2


Epoch #5: 1001it [00:01, 825.42it/s, env_step=5000, len=11, n/ep=1, n/st=10, player_1/loss=42.903, rew=10.00]          


Epoch #5: test_reward: -3177.800000 ± 9563.400000, best_reward: -326.000000 ± 672.814387 in #2


Epoch #6: 1001it [00:01, 832.21it/s, env_step=6000, len=7, n/ep=1, n/st=10, player_1/loss=165.781, rew=10.00]          


Epoch #6: test_reward: -7758.000000 ± 21111.768168, best_reward: -326.000000 ± 672.814387 in #2


Epoch #7: 1001it [00:01, 838.35it/s, env_step=7000, len=7, n/ep=3, n/st=10, player_1/loss=260.359, rew=10.00]          


Epoch #7: test_reward: -6835.100000 ± 12582.272962, best_reward: -326.000000 ± 672.814387 in #2


Epoch #8: 1001it [00:01, 838.95it/s, env_step=8000, len=7, n/ep=0, n/st=10, player_1/loss=287.218, rew=10.00]          


Epoch #8: test_reward: -3238.700000 ± 8137.768626, best_reward: -326.000000 ± 672.814387 in #2


Epoch #9: 1001it [00:01, 846.84it/s, env_step=9000, len=63, n/ep=1, n/st=10, player_1/loss=431.147, rew=-1373.00]      


Epoch #9: test_reward: -4443.500000 ± 7329.832321, best_reward: -326.000000 ± 672.814387 in #2


Epoch #10: 1001it [00:01, 846.08it/s, env_step=10000, len=36, n/ep=0, n/st=10, player_1/loss=631.407, rew=-308.00]     


Epoch #10: test_reward: -657.400000 ± 1988.882309, best_reward: -326.000000 ± 672.814387 in #2


Epoch #11: 1001it [00:01, 848.27it/s, env_step=11000, len=130, n/ep=0, n/st=10, player_1/loss=641.186, rew=-6318.00]   


Epoch #11: test_reward: -9930.200000 ± 22682.936251, best_reward: -326.000000 ± 672.814387 in #2


Epoch #12: 1001it [00:01, 839.62it/s, env_step=12000, len=10, n/ep=2, n/st=10, player_1/loss=465.093, rew=10.00]       


Epoch #12: test_reward: -14592.900000 ± 20469.948532, best_reward: -326.000000 ± 672.814387 in #2


Epoch #13: 1001it [00:01, 837.25it/s, env_step=13000, len=9, n/ep=0, n/st=10, player_1/loss=416.699, rew=10.00]        


Epoch #13: test_reward: -17.800000 ± 76.964667, best_reward: -17.800000 ± 76.964667 in #13


Epoch #14: 1001it [00:01, 850.02it/s, env_step=14000, len=9, n/ep=0, n/st=10, player_1/loss=277.915, rew=10.00]        


Epoch #14: test_reward: -10777.000000 ± 26710.130520, best_reward: -17.800000 ± 76.964667 in #13


Epoch #15: 1001it [00:01, 835.28it/s, env_step=15000, len=9, n/ep=0, n/st=10, player_1/loss=429.394, rew=10.00]        


Epoch #15: test_reward: -13995.900000 ± 21188.798968, best_reward: -17.800000 ± 76.964667 in #13


Epoch #16: 1001it [00:01, 835.54it/s, env_step=16000, len=7, n/ep=0, n/st=10, player_1/loss=315.852, rew=10.00]        


Epoch #16: test_reward: -22279.100000 ± 32188.836793, best_reward: -17.800000 ± 76.964667 in #13


Epoch #17: 1001it [00:01, 850.84it/s, env_step=17000, len=20, n/ep=0, n/st=10, player_1/loss=286.055, rew=-47.00]      


Epoch #17: test_reward: -11477.100000 ± 27605.375080, best_reward: -17.800000 ± 76.964667 in #13


Epoch #18: 1001it [00:01, 841.98it/s, env_step=18000, len=10, n/ep=1, n/st=10, player_1/loss=556.076, rew=-10.00]      


Epoch #18: test_reward: -907.500000 ± 2203.176219, best_reward: -17.800000 ± 76.964667 in #13


Epoch #19: 1001it [00:01, 847.53it/s, env_step=19000, len=60, n/ep=1, n/st=10, player_1/loss=320.179, rew=-891.00]     


Epoch #19: test_reward: -15361.500000 ± 38029.782298, best_reward: -17.800000 ± 76.964667 in #13


Epoch #20: 1001it [00:01, 841.06it/s, env_step=20000, len=13, n/ep=1, n/st=10, player_1/loss=511.158, rew=10.00]       


Epoch #20: test_reward: -31.500000 ± 124.500000, best_reward: -17.800000 ± 76.964667 in #13


Epoch #21: 1001it [00:01, 848.08it/s, env_step=21000, len=12, n/ep=0, n/st=10, player_1/loss=744.236, rew=10.00]       


Epoch #21: test_reward: -1640.500000 ± 4944.836929, best_reward: -17.800000 ± 76.964667 in #13


Epoch #22: 1001it [00:01, 830.31it/s, env_step=22000, len=11, n/ep=0, n/st=10, player_1/loss=417.822, rew=10.00]       


Epoch #22: test_reward: -2933.400000 ± 5841.504108, best_reward: -17.800000 ± 76.964667 in #13


Epoch #23: 1001it [00:01, 837.87it/s, env_step=23000, len=68, n/ep=0, n/st=10, player_1/loss=304.897, rew=-1331.00]    


Epoch #23: test_reward: -900.900000 ± 2726.039855, best_reward: -17.800000 ± 76.964667 in #13


Epoch #24: 1001it [00:01, 849.55it/s, env_step=24000, len=9, n/ep=0, n/st=10, player_1/loss=286.766, rew=10.00]        


Epoch #24: test_reward: -15004.700000 ± 24844.540358, best_reward: -17.800000 ± 76.964667 in #13


Epoch #25: 1001it [00:01, 834.43it/s, env_step=25000, len=9, n/ep=1, n/st=10, player_1/loss=485.533, rew=10.00]        


Epoch #25: test_reward: -30465.500000 ± 62724.906397, best_reward: -17.800000 ± 76.964667 in #13


Epoch #26: 1001it [00:01, 842.62it/s, env_step=26000, len=13, n/ep=0, n/st=10, player_1/loss=396.450, rew=10.00]       


Epoch #26: test_reward: -369.500000 ± 1138.500000, best_reward: -17.800000 ± 76.964667 in #13


Epoch #27: 1001it [00:01, 837.03it/s, env_step=27000, len=24, n/ep=1, n/st=10, player_1/loss=410.028, rew=-10.00]      


Epoch #27: test_reward: -4671.300000 ± 13224.626528, best_reward: -17.800000 ± 76.964667 in #13


Epoch #28: 1001it [00:01, 834.48it/s, env_step=28000, len=20, n/ep=1, n/st=10, player_1/loss=483.736, rew=-10.00]      


Epoch #28: test_reward: -3957.600000 ± 8337.879481, best_reward: -17.800000 ± 76.964667 in #13


Epoch #29: 1001it [00:01, 838.23it/s, env_step=29000, len=15, n/ep=1, n/st=10, player_1/loss=261.739, rew=10.00]       


Epoch #29: test_reward: -880.700000 ± 2665.440003, best_reward: -17.800000 ± 76.964667 in #13


Epoch #30: 1001it [00:01, 844.75it/s, env_step=30000, len=14, n/ep=0, n/st=10, player_1/loss=634.736, rew=-12.00]      


Epoch #30: test_reward: -270.900000 ± 842.700000, best_reward: -17.800000 ± 76.964667 in #13


Epoch #31: 1001it [00:01, 836.59it/s, env_step=31000, len=9, n/ep=0, n/st=10, player_1/loss=531.759, rew=10.00]        


Epoch #31: test_reward: -604.800000 ± 1573.099921, best_reward: -17.800000 ± 76.964667 in #13


Epoch #32: 1001it [00:01, 814.03it/s, env_step=32000, len=14, n/ep=0, n/st=10, player_1/loss=350.409, rew=-10.00]      


Epoch #32: test_reward: -1128.000000 ± 3003.524896, best_reward: -17.800000 ± 76.964667 in #13


Epoch #33: 1001it [00:01, 796.30it/s, env_step=33000, len=7, n/ep=0, n/st=10, player_1/loss=431.986, rew=10.00]        


Epoch #33: test_reward: -205.600000 ± 549.324713, best_reward: -17.800000 ± 76.964667 in #13


Epoch #34: 1001it [00:01, 807.35it/s, env_step=34000, len=8, n/ep=2, n/st=10, player_1/loss=409.936, rew=10.00]        


Epoch #34: test_reward: -11487.400000 ± 27904.362351, best_reward: -17.800000 ± 76.964667 in #13


Epoch #35: 1001it [00:01, 848.10it/s, env_step=35000, len=8, n/ep=0, n/st=10, player_1/loss=529.420, rew=10.00]        


Epoch #35: test_reward: -2873.400000 ± 8594.945866, best_reward: -17.800000 ± 76.964667 in #13


Epoch #36: 1001it [00:01, 852.65it/s, env_step=36000, len=7, n/ep=1, n/st=10, player_1/loss=1164.107, rew=10.00]       


Epoch #36: test_reward: -4555.300000 ± 9600.979753, best_reward: -17.800000 ± 76.964667 in #13


Epoch #37: 1001it [00:01, 850.94it/s, env_step=37000, len=7, n/ep=1, n/st=10, player_1/loss=578.868, rew=10.00]        


Epoch #37: test_reward: -4854.100000 ± 14092.061158, best_reward: -17.800000 ± 76.964667 in #13


Epoch #38: 1001it [00:01, 837.28it/s, env_step=38000, len=11, n/ep=3, n/st=10, player_1/loss=600.947, rew=10.00]       


Epoch #38: test_reward: -1231.200000 ± 3716.938116, best_reward: -17.800000 ± 76.964667 in #13


Epoch #39: 1001it [00:01, 850.36it/s, env_step=39000, len=10, n/ep=0, n/st=10, player_1/loss=466.308, rew=-10.00]      


Epoch #39: test_reward: -146.200000 ± 448.689157, best_reward: -17.800000 ± 76.964667 in #13


Epoch #40: 1001it [00:01, 844.81it/s, env_step=40000, len=9, n/ep=0, n/st=10, player_1/loss=760.185, rew=10.00]        


Epoch #40: test_reward: -2624.300000 ± 5391.149897, best_reward: -17.800000 ± 76.964667 in #13


Epoch #41: 1001it [00:01, 840.00it/s, env_step=41000, len=7, n/ep=0, n/st=10, player_1/loss=415.416, rew=10.00]        


Epoch #41: test_reward: -294.400000 ± 913.200000, best_reward: -17.800000 ± 76.964667 in #13


Epoch #42: 1001it [00:01, 851.93it/s, env_step=42000, len=25, n/ep=0, n/st=10, player_1/loss=699.360, rew=-137.00]     


Epoch #42: test_reward: -898.400000 ± 2701.880649, best_reward: -17.800000 ± 76.964667 in #13


Epoch #43: 1001it [00:01, 832.32it/s, env_step=43000, len=9, n/ep=0, n/st=10, player_1/loss=333.775, rew=10.00]        


Epoch #43: test_reward: -10679.200000 ± 28522.650591, best_reward: -17.800000 ± 76.964667 in #13


Epoch #44: 1001it [00:01, 850.36it/s, env_step=44000, len=7, n/ep=0, n/st=10, player_1/loss=997.477, rew=10.00]        


Epoch #44: test_reward: -184.600000 ± 577.164136, best_reward: -17.800000 ± 76.964667 in #13


Epoch #45: 1001it [00:01, 851.88it/s, env_step=45000, len=14, n/ep=0, n/st=10, player_1/loss=791.903, rew=-10.00]      


Epoch #45: test_reward: -1552.800000 ± 4675.073321, best_reward: -17.800000 ± 76.964667 in #13


Epoch #46: 1001it [00:01, 789.52it/s, env_step=46000, len=15, n/ep=0, n/st=10, player_1/loss=451.160, rew=10.00]       


Epoch #46: test_reward: 8.000000 ± 6.000000, best_reward: 8.000000 ± 6.000000 in #46


Epoch #47: 1001it [00:01, 826.81it/s, env_step=47000, len=7, n/ep=0, n/st=10, player_1/loss=325.211, rew=10.00]        


Epoch #47: test_reward: 6.000000 ± 8.000000, best_reward: 8.000000 ± 6.000000 in #46


Epoch #48: 1001it [00:01, 843.57it/s, env_step=48000, len=7, n/ep=0, n/st=10, player_1/loss=484.457, rew=10.00]        


Epoch #48: test_reward: -519.600000 ± 1284.527322, best_reward: 8.000000 ± 6.000000 in #46


Epoch #49: 1001it [00:01, 834.20it/s, env_step=49000, len=15, n/ep=0, n/st=10, player_1/loss=377.005, rew=10.00]       


Epoch #49: test_reward: 10.000000 ± 0.000000, best_reward: 10.000000 ± 0.000000 in #49


In [11]:
####################################################
# EXPERIMENT: VIEWING THE LEARNED POLICY
####################################################

# Get the environment settings
env = get_env()
observation_space = env.observation_space['observation'] if isinstance(env.observation_space, gym.spaces.Dict) else env.observation_space
state_shape = observation_space.shape or observation_space.n
action_shape = env.action_space.shape or env.action_space.n

# Configure the best agent
best_agent1 = cf_dqn_policy(state_shape= state_shape,
                            action_shape= action_shape)
best_agent1.load_state_dict(torch.load("./saved_variables/paper_notebooks/2/dqn_vs_random/best_policy_agent1.pth"))

# Watch the best agetn at work
watch(numer_of_games= 3,
      agent_player1= best_agent1)



Average steps of game:  16.333333333333332
Final mean reward agent 1: -11.666666666666666, std: 30.64129385141706
Final mean reward agent 2: -10.0, std: 0.0


<hr><hr>

## Discussion

The DQN agent has learned to stack coins in the hope that the other agent won't stack in that column and thus he will get a quick win.
This is a decent strategy against a random opponent but not that good against an actual human.
This also results in the agent getting stuck in a situation where it keeps stacking coins onto a full row, collecting many negative rewards.
This is likely to be resolved if more training is done but to make things more challenging for the smart DQN agent we will let him play against another DQN agent in the next notebook.

In [14]:
####################################################
# CLEAN VARIABLES
####################################################

del action_shape
del best_agent1
del env
del final_agent_player1
del final_agent_player2
del observation_space
del off_policy_traininer_results
del state_shape
